### ISSUE TITLE
Confirmar ao apagar intents, utters e stories

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#113]
Substituir o snackbar por um diálogo de confirmação que só apaga o item quando a pessoa clica Confirmar.

OU

Corrigir o comportamento com o snackbar, escondendo o item apagado imediatamente, ao invés de esperar o snack ser dispensado.

**Comment by rodmaia2099** [comment]
Referência do diálogo de confirmação: https://material-ui.com/components/dialogs/#alerts

**Comment by AmandaMuniz** [comment]
Following the procedures according to #153

**Comment by AmandaMuniz** [comment]
Following the procedures according to #153.

**Comment by AmandaMuniz** [comment]
After checking this issue, a pull request was found with the proper resolution. The code can be found on the branch master, and while running the software, it was possible to see the modifications working correctly. Therefore, this issue will be closed.
