### ISSUE TITLE
Edit name utter

### ISSUE THREAD

**Issue by EzequielDeOliveira** [lappis-unb/BotFlow#119]
Utter name, when changed don't send an error or success message, when press f5 list do update.

When the name is changed in utter, API response is 500, the flow is aborted and the list is not updated.

![Screenshot from 2019-09-18 11-00-14](https://user-images.githubusercontent.com/37127457/65155424-a3d65300-da03-11e9-9ace-7ad70ff0f639.png)

**Comment by rodrigocam** [comment]
Can you please test with the new commits on master? I think I fixed (: @EzequielDeOliveira

**Comment by EzequielDeOliveira** [comment]
i thought this problem is frontend but, when the API was updated it worked!  :) @rodrigocam

**Comment by AmandaMuniz** [comment]
Following the procedures according to #153.

**Comment by AmandaMuniz** [comment]
After checking this issue, I'll be moving this issue to 'done' and close it.
