### ISSUE TITLE
Bug campo de filtro no Chrome

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#122]

**Comment by Miguel-Alves** [comment]
Reviewing this issue based on #153;

**Comment by Miguel-Alves** [comment]
@rodmaia could you please describe the bug that was happening, so I can verify if It was solved?

**Comment by rodmaia** [comment]
This issue was poorly written by me and I have to confess that I can't recall what the bug was. Let's go over this when we do the call to review #145. 

Is there a pull request associated to this issue?

**Comment by rodmaia** [comment]
Did a quick check on my side and couldn't find any problems
