### ISSUE TITLE
Save button is disabled on valid cases

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#143]
In the edit Utter screen there are cases where the content is valid but the Save button is disabled all the same. Needs double checking.

**Comment by leticiaarj** [comment]
Fazendo.

**Comment by AmandaMuniz** [comment]
To enable the save button is necessary verification of the forms fields. This is the only check made to enable and disable the button. However, we cannot reproduce this bug. Not when editing an existent utter nor while creating a new one.

**Comment by rodmaia** [comment]
> To enable the save button is necessary verification of the forms fields. This is the only check made to enable and disable the button. However, we cannot reproduce this bug. Not when editing an existent utter nor while creating a new one.

Yeah, this is a tough one. I couldn't remember the specific situation off the top of my head. Any chance you can make an environment available for me to take a quick look 😬 ? It could be over a video conference if you only have a local environment.

**Comment by AmandaMuniz** [comment]
> > To enable the save button is necessary verification of the forms fields. This is the only check made to enable and disable the button. However, we cannot reproduce this bug. Not when editing an existent utter nor while creating a new one.
> 
> Yeah, this is a tough one. I couldn't remember the specific situation off the top of my head. Any chance you can make an environment available for me to take a quick look  ? It could be over a video conference if you only have a local environment.

At the moment, we only have a local environment. When is it possible for you to participate in a video conference?

**Comment by rodmaia** [comment]
After a collective review we couldn't reproduce the bug
