### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#146]
See also: #77

**Comment by WeillerFernandes** [comment]
Working on this issue

**Comment by rodmaia** [comment]
> Working on this issue

@WeillerFernandes assing the issue to yourself ;)

This issue was meant as a placeholder. You might want to break this issue in smaller issues to cover specific areas of the app.

**Comment by leticiaarj** [comment]
Reviewing the issue, according to #153.

**Comment by leticiaarj** [comment]
The issue has no description. Likewise, there is no specification as to whether the tests are Frontend or Backend, and which frameworks are used.

**Comment by rodmaia** [comment]
As mentioned above, this issue was meant to be a placeholder. Consider it an opportunity to understand and map the current test coverage on everything: frontend, backend and API. We can open new issues to write tests for what's missing. 

Feel free to use what you believe to the best framework. @RochaCarla care to chime in?
