### ISSUE TITLE
Build API does not work

### ISSUE THREAD

**Issue by BrunaNayara** [lappis-unb/BotFlow#37]
When trying to run the project `docker-compose up --build`, I get this error 
![image](https://user-images.githubusercontent.com/4125846/59108489-5ed55780-8911-11e9-96d7-f1defbd83b17.png)

**Comment by ygortgaleno** [comment]
If you are running the project for the first time, you need to create inside private's folder a private and public JWT keys both in RSA256

- jwtRS256.key for private key
- jwtRSA256.pub for public key

After this the project will be abble to run, do this and answer here if the issue persist

**Comment by rodmaia2099** [comment]
@BrunaNayara did that fix the issue for you?
