### ISSUE TITLE
(1) Translate NGINX config info to EN

### ISSUE THREAD

**Issue by rodmaia2099** [lappis-unb/BotFlow#39]
**Tasks**

- [x] Translate NGINX config info to EN

**Acceptance criteria**

- [x] English config info is available on the wiki

**Comment by gabibguedes** [comment]
Link: https://github.com/lappis-unb/BotFlow/wiki/Nginx-Configuration-on-Virtual-Machine

@rodmaia2099 Could you review it please? :)

**Comment by rodmaia2099** [comment]
@gabibguedes it seems good to me!  I made a few changes for clarification.

**Comment by rodmaia2099** [comment]
@gabibguedes, you might want to cross link the PT and EN versions on the wiki.
