### ISSUE TITLE
Document test strategies

### ISSUE THREAD

**Issue by rodmaia** [lappis-unb/BotFlow#77]
Document all the research done about the implementation of tests on the project

**Comment by rodmaia2099** [comment]
@eduardonunes2525 could you add the required details for the issue, pls?

**Comment by eduardonunes2525** [comment]
A pesquisa superficial realizada a respeito dos testes de front-end basea-se em entender quais são os tipos de testes que devem ser implementados e quais são os tipos de teste de front-end.

Materiais relevantes encontrados:
https://dev.to/christopherkade/introduction-to-front-end-unit-testing-510n
https://medium.com/front-end-weekly/unit-testing-front-end-38b9bf1de079
https://www.freecodecamp.org/news/the-front-end-test-pyramid-rethink-your-testing-3b343c2bca51/

A respeito de testes unitários a ferramenta mais utilizada com base no resultado das pequisas foi: [Jest](https://jestjs.io/).

**Comment by rodmaia** [comment]
Moved to #146
