### ISSUE TITLE
Certificado inválido API

### ISSUE THREAD

**Issue by victorcmoura** [lappis-unb/BotFlow#96]
É necessário verificar o que aconteceu com o script de certificado.  O Diniz já foi notificado do problema e estará disponível para ajudar na quinta feira (12/09)

**Comment by victorcmoura** [comment]
A parte de configuração do certificado não estava padronizada. O esforço para refazer era maior do que aguardar a estabilização do deploy do Rancher.

Hoje, 18/09, o front está no Rancher. A API ainda apresenta um problema de conexão com o banco. Resolvendo este problema, a stack toda estará no Rancher, com certificado gerado automaticamente.

**Comment by rodmaia** [comment]
No longer relevant
